### PR TITLE
Wrap all long values in description list

### PR DESCRIPTION
**Pull request by lukaw3d**
| Before | After | 
| --- | --- |
| localhost_1234_testnet_sapphire_tx_0x12106a139c9eb799f25b2fd3879827c23c737debefa63da8569560ba556e163c (1) | localhost_1234_testnet_sapphire_tx_0x12106a139c9eb799f25b2fd3879827c23c737debefa63da8569560ba556e163c |

### CODE REVIEW

**Comment by lukaw3d** [comment]
@donouwens thoughts? this seems like a good fallback if mobile+tablet designs don't capture everything

**Comment by csillag** [comment]
Nice, but I don't get why `Encrypted data` looks like that (on the "before" image), since we already have wrapping enabled at https://github.com/oasisprotocol/explorer/blob/42e96f394b137ded663c53b84d798e930b476771/src/app/components/LongDataDisplay/index.tsx#L21

And it does work, down to a specific width, and then stops working. I think that would be worth a separate fix.

**Comment by lukaw3d** [comment]
> @csillag And it does work, down to a specific width, and then stops working. I think that would be worth a separate fix.

Looks like it stops working at the width of tx hash (tx hash didn't have wrapping, and it extended the parent element width)

**Comment by csillag** [comment]
Changelog fragment seems to be missing

**Pull request merged**
