### PR TITLE
Fix account redirection logic for checksum capitalized addresses

### PR DESCRIPTION
**Pull request by lukaw3d**
Fixes https://github.com/oasisprotocol/explorer/commit/a59aae37d64c1b208c62f85fc3f5066a7d2e0be9

### CODE REVIEW

**Review by lubej — APPROVED** [review]

**Review by csillag — APPROVED** [review]
Oh. I was thinking about lowercasing the addresses before comparison, but then I assumed that Nexus is already lowercasing it during the indexing. I forgot about checksum accounts.

LGTM.

**Comment by buberdds** [comment]
@lukaw3d do we want to include it in a release? if that's a case let's switch to bugfix

**Comment by csillag** [comment]
> @lukaw3d do we want to include it in a release? if that's a case let's switch to bugfix

I don't think it's critical.

The worst think that can happen without this fix is that when someone searches for an account by a checksum capitalizd address, and there is only one result, and we redirect to it, then the URL will have an unnecessary query param, which won't cause any technical problem.

**Comment by lukaw3d** [comment]
yeah not critical

**Pull request merged**
