### PR TITLE
Support scrolling to token list

### PR DESCRIPTION
**Pull request by csillag**
when clicking on the more tokens link on the accounts page.

Might be related to #385.

### CODE REVIEW

**Review by buberdds — APPROVED** [review]

**Comment by lukaw3d** [comment]
Things are still inconsistent at scrolling, not sure if intentionally
image

- "+1 more" pill scrolls: https://oasis-explorer.pages.dev/mainnet/emerald/account/0xBA504818FdD8D3dBA2Ef8fD9B4F4D5c71aD1d1D3/tokens/erc-20#tokens
- "177611.8 YUZU" pill doesn't scroll: https://oasis-explorer.pages.dev/mainnet/emerald/account/0xBA504818FdD8D3dBA2Ef8fD9B4F4D5c71aD1d1D3/tokens/erc-20#oasis1qzk2y3kvp7000qck8zjsmwadhy3lumnmdys20x3z
- "ERC-20" tab doesn't scroll: https://oasis-explorer.pages.dev/mainnet/emerald/account/0xBA504818FdD8D3dBA2Ef8fD9B4F4D5c71aD1d1D3/tokens/erc-20

**Comment by csillag** [comment]
> "+1 more" pill scrolls:

Yes

> "177611.8 YUZU" pill doesn't scroll

For me, [it does](https://oasis-explorer.pages.dev/mainnet/emerald/account/0xBA504818FdD8D3dBA2Ef8fD9B4F4D5c71aD1d1D3/tokens/erc-20#oasis1qzk2y3kvp7000qck8zjsmwadhy3lumnmdys20x3z)! (But you need a really short window to see it.)

> "ERC-20" tab doesn't scroll:

That's not intentional. Will fix.

**Comment by csillag** [comment]
> > "177611.8 YUZU" pill doesn't scroll

> For me, [it does](https://oasis-explorer.pages.dev/mainnet/emerald/account/0xBA504818FdD8D3dBA2Ef8fD9B4F4D5c71aD1d1D3/tokens/erc-20#oasis1qzk2y3kvp7000qck8zjsmwadhy3lumnmdys20x3z)! (But you need a really short window to see it.)

Ohh... it's inconsistent. (Scrolls when clicked or reloading, doesn't scroll when opening in new tab.)

**Comment by csillag** [comment]
Check YUZU here: https://7af44b1d.oasis-explorer.pages.dev/mainnet/emerald/account/0xBA504818FdD8D3dBA2Ef8fD9B4F4D5c71aD1d1D3/tokens/erc-20#oasis1qzk2y3kvp7000qck8zjsmwadhy3lumnmdys20x3z

Check the ERC-20 tab here: https://7af44b1d.oasis-explorer.pages.dev/mainnet/emerald/account/0xBA504818FdD8D3dBA2Ef8fD9B4F4D5c71aD1d1D3/tokens/erc-20#tokens

PR is at #419

**Pull request merged**
