### PR TITLE
Follow api stats changes

### PR DESCRIPTION
**Pull request by csillag**
See the API changes described here: https://github.com/oasisprotocol/nexus/pull/477

### CODE REVIEW

**Comment by csillag** [comment]
I massaged the code until in _syntactically_ makes sense, but I'm not sure if it's also _semantically_ correct. @buberdds can you comment on this when you are back? Thanks.

**Comment by csillag** [comment]
So @buberdds, we no longer this one, since you have covered all the changes in #812, right?

**Comment by buberdds** [comment]
yes, that's correct

**Comment by csillag** [comment]
Superseded by https://github.com/oasisprotocol/explorer/pull/812, so closing

**Pull request closed without merging**
